In [5]:
import torch
print("Torch Version:",torch.__version__)

Torch Version: 2.5.1+cpu


In [6]:
!nvidia-smi

Sat Jan 18 21:20:56 2025       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 512.78       Driver Version: 512.78       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   53C    P8     5W /  N/A |      0MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [8]:
if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))
    print('cuda')

In [12]:
#Create empty matrix and taking garable values for Main memory
a = torch.empty(2,3)
print(type(a))
a

<class 'torch.Tensor'>


tensor([[1.7602e+13, 1.9142e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [13]:
# Fill th vale inside the a empty tensor
a.fill_(0)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [14]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
torch.ones(4,2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [20]:
torch.rand(3,2)

tensor([[0.7415, 0.8168],
        [0.8852, 0.8984],
        [0.7053, 0.5895]])

In [27]:
torch.manual_seed(10)
torch.rand(3,2)

tensor([[0.4581, 0.4829],
        [0.3125, 0.6150],
        [0.2139, 0.4118]])

In [29]:
torch.manual_seed(11)
torch.rand(3,2)

tensor([[0.1490, 0.4866],
        [0.9857, 0.1684],
        [0.5839, 0.6936]])

In [31]:
torch.tensor([[1,2,3],[3,4,5]])

tensor([[1, 2, 3],
        [3, 4, 5]])

In [32]:
torch.arange(3,10)

tensor([3, 4, 5, 6, 7, 8, 9])

In [33]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

In [34]:
torch.linspace(0,10,16)

tensor([ 0.0000,  0.6667,  1.3333,  2.0000,  2.6667,  3.3333,  4.0000,  4.6667,
         5.3333,  6.0000,  6.6667,  7.3333,  8.0000,  8.6667,  9.3333, 10.0000])

In [35]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [40]:
torch.full((4,4),3)

tensor([[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]])

In [41]:
x = torch.tensor([[1,2,3],[3,4,5]])
x.shape

torch.Size([2, 3])

In [42]:
torch.empty_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [43]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [45]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.5831, 0.1284, 0.5721],
        [0.9248, 0.2693, 0.7825]])

In [46]:
print(x+2)
print(x-2)
print(x*3)
print(x/4)

tensor([[3, 4, 5],
        [5, 6, 7]])
tensor([[-1,  0,  1],
        [ 1,  2,  3]])
tensor([[ 3,  6,  9],
        [ 9, 12, 15]])
tensor([[0.2500, 0.5000, 0.7500],
        [0.7500, 1.0000, 1.2500]])


In [47]:
b = torch.tensor([1,-2,3,-4])
torch.abs(b)

tensor([1, 2, 3, 4])

In [49]:
torch.neg(b)

tensor([-1,  2, -3,  4])

In [50]:
d = torch.tensor([1.9,2.3,3.7,4.4])
torch.round(d)

tensor([2., 2., 4., 4.])

In [51]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [52]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [56]:
torch.randint(size=(3,4),low=0,high=10)

tensor([[3, 4, 0, 6],
        [9, 1, 8, 7],
        [9, 8, 5, 1]])

In [57]:
torch.randint(size=(3,4),low=0,high=10,dtype=torch.float32)

tensor([[2., 5., 7., 8.],
        [1., 2., 1., 5.],
        [3., 4., 0., 2.]])

In [74]:
a = torch.randint(size=(3,4),low=0,high=10,dtype=torch.float32)
a

tensor([[2., 5., 9., 2.],
        [6., 8., 4., 8.],
        [5., 7., 7., 4.]])

In [75]:
torch.sum(a)

tensor(67.)

In [76]:
torch.sum(a,dim=0)

tensor([13., 20., 20., 14.])

In [77]:
torch.sum(a,dim=1)

tensor([18., 26., 23.])

In [78]:
torch.mean(a,dtype=torch.float32)

tensor(5.5833)

In [79]:
torch.mean(a,dim=1,dtype=torch.float32)

tensor([4.5000, 6.5000, 5.7500])

In [80]:
torch.mean(a,dim=0,dtype=torch.float32)

tensor([4.3333, 6.6667, 6.6667, 4.6667])

In [81]:
torch.max(a)

tensor(9.)

1. argmax it is giving me index of highest value in matrix
2. argmin it is giving me index of lowest value in matrix

In [82]:
torch.argmin(a)

tensor(0)

In [83]:
torch.argmax(a)

tensor(2)

In [91]:
f = torch.randint(1,10,(2,3))
g = torch.randint(1,10,(3,2))

print(f)
print(g)

tensor([[3, 8, 1],
        [8, 3, 6]])
tensor([[6, 1],
        [8, 5],
        [7, 2]])


In [92]:
torch.matmul(f,g)

tensor([[ 89,  45],
        [114,  35]])

In [94]:
torch.transpose(f,0,1)

tensor([[3, 8],
        [8, 3],
        [1, 6]])

In [96]:
m = torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)

torch.inverse(m)

tensor([[-0.1429,  0.3095,  0.0238],
        [-0.2143,  0.1310,  0.2024],
        [ 0.3571, -0.2738, -0.0595]])

In [97]:
torch.exp(m)

tensor([[ 54.5981,   2.7183, 148.4132],
        [148.4132,   1.0000,   7.3891],
        [  2.7183, 403.4288,  54.5981]])

In [99]:
torch.softmax(m,0)

tensor([[0.2654, 0.0067, 0.7054],
        [0.7214, 0.0025, 0.0351],
        [0.0132, 0.9909, 0.2595]])